/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.cloudevents;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.*;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Representation of a JSON Value */
@org.apache.avro.specific.AvroGenerated
public class AvroCloudEventData extends SpecificRecordBase implements SpecificRecord {
  private static final long serialVersionUID = 6655532353752151588L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroCloudEventData\",\"namespace\":\"io.cloudevents\",\"doc\":\"Representation of a JSON Value\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"map\",\"values\":[\"null\",\"boolean\",{\"type\":\"map\",\"values\":\"AvroCloudEventData\"},{\"type\":\"array\",\"items\":\"AvroCloudEventData\"},\"double\",\"string\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroCloudEventData> ENCODER =
      new BinaryMessageEncoder<AvroCloudEventData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroCloudEventData> DECODER =
      new BinaryMessageDecoder<AvroCloudEventData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroCloudEventData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroCloudEventData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroCloudEventData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroCloudEventData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroCloudEventData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroCloudEventData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroCloudEventData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroCloudEventData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.Map<java.lang.CharSequence,java.lang.Object> value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroCloudEventData() {}

  /**
   * All-args constructor.
   * @param value The new value for value
   */
  public AvroCloudEventData(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
    this.value = value;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.util.Map<java.lang.CharSequence,java.lang.Object>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Object> getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
    this.value = value;
  }

  /**
   * Creates a new AvroCloudEventData RecordBuilder.
   * @return A new AvroCloudEventData RecordBuilder
   */
  public static AvroCloudEventData.Builder newBuilder() {
    return new AvroCloudEventData.Builder();
  }

  /**
   * Creates a new AvroCloudEventData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroCloudEventData RecordBuilder
   */
  public static AvroCloudEventData.Builder newBuilder(AvroCloudEventData.Builder other) {
    if (other == null) {
      return new AvroCloudEventData.Builder();
    } else {
      return new AvroCloudEventData.Builder(other);
    }
  }

  /**
   * Creates a new AvroCloudEventData RecordBuilder by copying an existing AvroCloudEventData instance.
   * @param other The existing instance to copy.
   * @return A new AvroCloudEventData RecordBuilder
   */
  public static AvroCloudEventData.Builder newBuilder(AvroCloudEventData other) {
    if (other == null) {
      return new AvroCloudEventData.Builder();
    } else {
      return new AvroCloudEventData.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroCloudEventData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroCloudEventData>
    implements org.apache.avro.data.RecordBuilder<AvroCloudEventData> {

    private java.util.Map<java.lang.CharSequence,java.lang.Object> value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AvroCloudEventData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroCloudEventData instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroCloudEventData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Object> getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public AvroCloudEventData.Builder setValue(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public AvroCloudEventData.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroCloudEventData build() {
      try {
        AvroCloudEventData record = new AvroCloudEventData();
        record.value = fieldSetFlags()[0] ? this.value : (java.util.Map<java.lang.CharSequence,java.lang.Object>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroCloudEventData>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroCloudEventData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroCloudEventData>
    READER$ = (org.apache.avro.io.DatumReader<AvroCloudEventData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










